sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.local
    - vendor

env:
  global:
    - COMPOSER_ARGS="--no-interaction"
    - LEGACY_DEPS="phpunit/phpunit zendframework/zend-stdlib zendframework/zend-eventmanager  zendframework/zend-servicemanager"

matrix:
  fast_finish: true
  include:
    - php: 5.5
    - php: 5.5
      env:
        - ZEND_SERVICEMANAGER_VERSION="^2.7.5"
        - ZEND_EVENTMANAGER_VERSION="^2.2.1"
    - php: 5.6
      env:
        - EXECUTE_CS_CHECK=true
    - php: 5.6
      env:
        - ZEND_SERVICEMANAGER_VERSION="^2.7.5"
        - ZEND_EVENTMANAGER_VERSION="^2.2.1"
    - php: 7
    - php: 7
      env:
        - ZEND_SERVICEMANAGER_VERSION="^2.7.5"
        - ZEND_EVENTMANAGER_VERSION="^2.2.1"
    - php: hhvm
    - php: hhvm
      env:
        - ZEND_SERVICEMANAGER_VERSION="^2.7.5"
        - ZEND_EVENTMANAGER_VERSION="^2.2.1"
  allow_failures:
    - php: 5.5

before_install:
  - composer self-update
  - if [[ $ZEND_SERVICEMANAGER_VERSION != '' ]]; then composer require --dev --no-update "zendframework/zend-servicemanager:$ZEND_SERVICEMANAGER_VERSION" ; fi
  - if [[ $ZEND_SERVICEMANAGER_VERSION == '' ]]; then composer require --dev --no-update "zendframework/zend-servicemanager:^3.0.3" ; fi
  - if [[ $ZEND_EVENTMANAGER_VERSION != '' ]]; then composer require --dev --no-update "zendframework/zend-eventmanager:$ZEND_EVENTMANAGER_VERSION" ; fi
  - if [[ $ZEND_EVENTMANAGER_VERSION == '' ]]; then composer require --dev --no-update "zendframework/zend-eventmanager:^3.0.1" ; fi


install:
  - travis_retry composer install $COMPOSER_ARGS --ignore-platform-reqs --prefer-dist --no-scripts
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.5" ]]; then travis_retry composer require phpunit/phpunit:^4.8 --with-dependencies && composer update $COMPOSER_ARGS --with-dependencies $LEGACY_DEPS ; fi

script:
  - composer test
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then composer cs ; fi
